export const ADD_POEM = 'ADD_POEM'
export const GET_POEM = 'GET_POEM'
export const GET_POEMS = 'GET_POEMS'
export const POEM_ERROR = 'POEM_ERROR'
export const ADD_LIKE = 'ADD_LIKE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
