export const ADD_POEM = 'ADD_POEM'
export const GET_POEM = 'GET_POEM'
export const GET_POEMS = 'GET_POEMS'
export const POEM_ERROR = 'POEM_ERROR'
export const ADD_LIKE = 'ADD_LIKE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const LOAD_LIKES = 'LOAD_LIKES'
export const ADD_LIKE_ARR = 'ADD_LIKE_ARR'
export const REMOVE_LIKE_ARR = 'REMOVE_LIKE_ARR'

export const LOAD_USER = 'LOAD_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_ERROR = 'USER_ERROR'
